branches:
  only:
  - master
language: python
python:
- 2.7
install:
- git clone -b develop --single-branch https://github.com/grow/pygrow.git
- cd pygrow
- pip install -r requirements.txt
- python setup.py install
- cd ..
script: ./pygrow/bin/grow deploy --noconfirm growsdk.org
