sudo: false
language: python
python: 2.7
cache: pip
install: pip install grow
script:
  - grow build
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST_BRANCH" == "" ] ; then grow deploy --noconfirm grow.io ; fi
