version: 2
jobs:
  build:
    working_directory: ~/grow
    docker:
      - image: grow/baseimage:latest
    steps:
      - checkout

      - run:
          name: Test Build
          command: grow build

      - run:
          name: Deploy to Prod
          command: if [ "$CIRCLE_BRANCH" == "master" ] && [ "$CIRCLE_PULL_REQUEST" == "" ] ; then grow deploy --noconfirm grow.io ; fi

      - restore_cache:
          keys:
            - gem-cache-{{ .Branch }}
            - gem-cache

      - run: gem install compass percy-cli

      - save_cache:
          key: gem-cache-{{ .Branch }}
          paths:
            - vendor/bundle

      - save_cache:
          key: gem-cache
          paths:
            - vendor/bundle

      - run:
          name: Percy Snapshots
          command: percy snapshot --widths "412,1280" --enable_javascript build/
