version: 2
jobs:
  build:
    working_directory: ~/grow
    docker:
      - image: grow/base:master
    steps:
      - checkout

      - restore_cache:
          keys:
            - &cache_key grow-cache-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}

      - run:
          name: Grow Install
          command: grow install

      - save_cache:
          key: *cache_key
          paths:
            - node_modules

      - run:
          name: Grow Build
          command: grow build --deployment grow.io

      - run:
          name: Deploy to Prod
          command: if [ "$CIRCLE_BRANCH" == "master" ] && [ "$CIRCLE_PULL_REQUEST" == "" ] ; then grow deploy --noconfirm grow.io ; fi

      - persist_to_workspace:
          root: ~/grow
          paths:
            - build/*

  snapshot:
    working_directory: ~/grow
    docker:
    - image: zoramite/percy-base:latest

    steps:
    - attach_workspace:
        at: ~/grow
    - run:
        name: Percy Snapshots
        command: percy snapshot --widths "412,1280" --enable_javascript build/
workflows:
  version: 2
  build:
    jobs:
    - build
    - snapshot:
        requires:
        - build
