version: 2
jobs:
  build:
    working_directory: ~/growio
    docker:
      - image: grow/baseimage:latest
    steps:
      - checkout

      - run:
          name: Test Build
          command: grow build

      - run:
          name: Deploy to Prod
          command: if [ "$CIRCLE_BRANCH" == "master" ] && [ "$CIRCLE_PULL_REQUEST" == "" ] ; then grow deploy --noconfirm grow.io ; fi
