version: 2
jobs:
  build:
    working_directory: ~/grow
    docker:
      - image: grow/baseimage:latest
    steps:
      - checkout

      - run:
          name: Test Build
          command: grow build

      - run:
          name: Deploy to Prod
          command: if [ "$CIRCLE_BRANCH" == "master" ] && [ "$CIRCLE_PULL_REQUEST" == "" ] ; then grow deploy --noconfirm grow.io ; fi

      - run:
          name: Install Gems
          command: gem install compass percy-cli

      - run:
          name: Percy Snapshots
          command: percy snapshot --widths "412,1280" --enable_javascript build/
