$title: Grow Open Source Project
$titles:
  nav: About
description: An open source, Git-based static site generator for rapid, content-driven website management and production.

composite_files:
- home

partials:
- partial: hero
  title: Grow
  subtitle: Grow is an open source project.
  image: !g.url /static/images/grow.svg
  cta:
    icon: code
    title: GitHub
    url: https://github.com/grow/grow
- partial: features
  features:
  - title: Grow's mission is to bring joy to building and launching microsites
    image: !g.url /static/images/launch.svg
    description:
    - |
      We want Grow to be the canonical way for teams and individuals to build, launch, and
      maintain high-quality, content-rich web sites. It's architected to work for humans, to allow
      people pair it with their own development tools, to run locally and in the cloud, and to
      bring simplicity to web site management.
    - |
      Grow (the app) and the stuff you make with it (your sites) are portable. You can run Grow
      anywhere, and you can take your content anywhere because your content is stored as flat
      files. There will never be lock-in with Grow.
  - title: Get involved
    image: !g.url /static/images/pencil.svg
    description:
    - |
      Grow is open source and you can help shape its future by contributing code, filing issues,
      joining the discussion, and making feature requests.
    - You can contribute code by sending pull requests to the open source project.
    links:
    - title: Source Code
      url: https://github.com/grow/grow
    - title: Issues and Milestones
      url: https://github.com/grow/grow/issues
    - title: Mailing List
      url: https://groups.google.com/forum/#!forum/growsdk
    - title: Contributors
      url: https://github.com/grow/grow/graphs/contributors
    - title: Organization
      url: https://github.com/grow
  - title: Technology
    image: !g.url /static/images/light.svg
    description: |
      Grow is written in Python and projects are file-based and backed by Git. Grow is a static site
      generator – meaning you can use it to build and deploy sites almost anywhere
  - title: Roadmap
    image: !g.url /static/images/map.svg
    description: |
      Interested in seeing what Grow will be adding in the future? Checkout the GitHub issue tracker
      to see what is in the works.
    links:
    - title: Grow Issues and Milestones
      url: https://github.com/grow/grow/issues
